$config = Get-Content "C:\Dev\projects\guavacheck\features.json" -Raw | ConvertFrom-Json

Write-Host ""
Write-Host "==============================="
Write-Host "GUAVACHECK DEV OS 2.0"
Write-Host "==============================="
Write-Host ""

foreach ($feature in $config.features) {

    if ($feature.enabled -eq $true) {

        $route = $feature.route
        $routeName = $feature.name

        $path = "C:\Dev\projects\guavacheck\app$route"

        if (!(Test-Path $path)) {
            New-Item -ItemType Directory -Path $path -Force
        }

        $pageFile = "$path\page.jsx"

        $content = @"
export default function Page() {
  return (
    <main style={{padding:40}}>
      <h1>$($routeName.ToUpper())</h1>
      <p>Generated by Guava Dev OS</p>
    </main>
  )
}
"@

        Set-Content -Path $pageFile -Value $content

        Write-Host "[ACTIVE] $routeName"
    }

    else {
        Write-Host "[DISABLED] $($feature.name)"
    }
}

Write-Host ""
Write-Host "DEV OS GENERATION COMPLETE"
