import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const { report } = await req.json();

    if (!report) {
      return new Response(
        JSON.stringify({ error: "Missing report" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    const pdf = await PDFDocument.create();
    const page = pdf.addPage([600, 850]);

    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

    let y = 800;

    const draw = (text: string, size = 12, isBold = false) => {
      page.drawText(text || "", {
        x: 50,
        y,
        size,
        font: isBold ? bold : font,
        color: rgb(0, 0, 0)
      });
      y -= size + 6;
    };

    const line = () => {
      y -= 10;
      page.drawLine({
        start: { x: 50, y },
        end: { x: 550, y },
        thickness: 1,
        color: rgb(0.85, 0.85, 0.85)
      });
      y -= 15;
    };

    // HEADER
    draw("AUSTIN CONSTRUCTION REPORT", 16, true);
    draw("Generated by Guava AI System", 10);
    line();

    // PROJECT
    draw("PROJECT DETAILS", 13, true);
    draw("Location: " + (report?.project?.location || "N/A"));
    draw("Size: " + (report?.project?.sqm || 0) + " sqm");
    draw("Level: " + (report?.project?.level || "standard"));
    line();

    // SUMMARY
    draw("SUMMARY", 13, true);
    draw("Total Cost: NGN " + (report?.summary?.totalCost || 0));
    draw("Duration: " + (report?.summary?.durationWeeks || 0) + " weeks");
    draw("Cost per sqm: NGN " + (report?.summary?.costPerSqm || 0));
    line();

    // BREAKDOWN
    draw("BOQ BREAKDOWN", 13, true);

    const breakdown = report?.summary?.breakdown || {};

    Object.entries(breakdown).forEach(([k, v]) => {
      draw(k + ": NGN " + v);
    });

    line();

    // PHASES
    draw("PHASE TIMELINE", 13, true);

    for (const p of report?.phases || []) {
      draw(p.phase + " → " + p.durationWeeks + " weeks → NGN " + p.cost);
    }

    line();

    // INSIGHTS
    draw("INSIGHTS", 13, true);

    for (const i of report?.insights || []) {
      draw("• " + i);
    }

    line();

    draw("© Austin AI - Guava Networks", 10);

    const pdfBytes = await pdf.save();

    return new Response(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=austin-report.pdf"
      }
    });

  } catch (err: any) {
    return new Response(
      JSON.stringify({ error: String(err?.message || err) }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" }
      }
    );
  }
}






