-- ==========================================================
-- GUAVACHECK ENGINEERING SNAPSHOTS
-- Existing table managed by Supabase
-- No migration required.
-- ==========================================================