export enum DomainEvent {
  PROPERTY_CREATED = "PROPERTY_CREATED",

  PROPERTY_UPDATED = "PROPERTY_UPDATED",

  PROPERTY_DELETED = "PROPERTY_DELETED",

  PROPERTY_VERIFIED = "PROPERTY_VERIFIED",

  PROPERTY_VALUED = "PROPERTY_VALUED",

  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",

  SURVEY_ANALYZED = "SURVEY_ANALYZED",

  TITLE_VERIFIED = "TITLE_VERIFIED",

  AI_REQUEST = "AI_REQUEST",

  AI_RESPONSE = "AI_RESPONSE",

  AI_REPORT_CREATED = "AI_REPORT_CREATED",

  MARKET_UPDATED = "MARKET_UPDATED",

  PORTFOLIO_UPDATED = "PORTFOLIO_UPDATED",

  USER_JOINED = "USER_JOINED",

  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",

  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",

  NOTIFICATION_CREATED = "NOTIFICATION_CREATED",
}
